/**
* Nudsf_DataRepository
* Nudsf Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * RecordCRUDApi.h
 *
 * 
 */

#ifndef _DATA_EXPOSURE_API_H_
#define _DATA_EXPOSURE_API_H_


#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>
#include <pistache/optional.h>

#include <string>
#include <vector>
#include "TransData.hpp"
#include <iostream>
#include <stdlib.h>

namespace oai {
namespace amf {
namespace api {

using namespace oai::amf::model;

class  DataExposureApi {
public:
    DataExposureApi(std::shared_ptr<Pistache::Rest::Router>);
    virtual ~DataExposureApi() {}
    void init();

    const std::string base = "/data_exposure/v1";

private:
    void setupRoutes();

    void getNFService(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    std::shared_ptr<Pistache::Rest::Router> router;     

};

}
}
}

#endif /* RecordCRUDApi_H_ */

