/**
 * Namf_Communication
 * AMF Communication Service © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * IndividualSubscriptionDocumentApiImpl.h
 *
 *
 */

#ifndef INDIVIDUAL_SUBSCRIPTION_DOCUMENT_API_IMPL_H_
#define INDIVIDUAL_SUBSCRIPTION_DOCUMENT_API_IMPL_H_

#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <IndividualSubscriptionDocumentApi.h>

#include <pistache/optional.h>

#include "ProblemDetails.h"
#include "SubscriptionData.h"
#include <string>
#include "TransData.hpp"
#include "amf_app.hpp"

namespace oai {
namespace amf {
namespace api {

using namespace oai::amf::model;

class IndividualSubscriptionDocumentApiImpl
    : public oai::amf::api::IndividualSubscriptionDocumentApi {
 public:
  IndividualSubscriptionDocumentApiImpl(
      std::shared_ptr<Pistache::Rest::Router>,
      amf_application::amf_app* amf_app_inst);
  ~IndividualSubscriptionDocumentApiImpl() {}

  void a_mf_status_change_subscribe_modfy(
      const std::string& subscriptionId,
      const SubscriptionData& subscriptionData,
      Pistache::Http::ResponseWriter& response);
  void a_mf_status_change_un_subscribe(
      const std::string& subscriptionId,
      Pistache::Http::ResponseWriter& response);
    void gnb_message_from_plugin(const std::uint32_t &assoc_id, const std::uint16_t &stream ,TransData transdata, Pistache::Http::ResponseWriter &response);

 private:
  amf_application::amf_app* m_amf_app;
};

}  // namespace api
}  // namespace amf
}  // namespace oai

#endif
