/**
* Nudsf_DataRepository
* Nudsf Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0-alpha.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Record.h
 *
 * Definition of a Record
 */

#ifndef Record_H_
#define Record_H_


#include "RecordMeta.h"
#include <vector>
//#include "AnyType.h"
#include <nlohmann/json.hpp>

namespace oai {
namespace amf {
namespace model {

// struct block{
//     std::string Content_id ;
//     std::string Content_type;
//     std::string caontent;
// };

/// <summary>
/// Definition of a Record
/// </summary>
class  Record
{
public:
    Record();
    virtual ~Record();

    void validate();

    /////////////////////////////////////////////
    /// Record members

    /// <summary>
    /// 
    /// </summary>
    RecordMeta getMeta() const;
    void setMeta(RecordMeta const& value);
    /// <summary>
    /// list of opaque Block&#39;s in this Record
    /// </summary>
    std::set<nlohmann::json> getBlocks() const;
    void setBlocks(std::set<nlohmann::json> const& value);
    bool blocksIsSet() const;
    void unsetBlocks();

    friend void to_json(nlohmann::json& j, const Record& o);
    friend void from_json(const nlohmann::json& j, Record& o);
protected:
    RecordMeta m_Meta;

    //std::vector< std::map<std::string, std::string>> m_Blocks;
    //std::vector< std::map<std::string, nlohmann::json>> m_Blocks;
    std::set<nlohmann::json> m_Blocks;
    bool m_BlocksIsSet;
};

}
}
}

#endif /* Record_H_ */
