/**
 * Namf_Communication
 * AMF Communication Service © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "TransData.hpp"
#include <iostream>
namespace oai {
namespace amf {
namespace model {

TransData::TransData() {
  m_transdata   = "";
}

TransData::~TransData() {}

std::string TransData::get_amf_data()
{
  return m_transdata;
}

void to_json(nlohmann::json& j, const TransData& o) {
  j                 = nlohmann::json();
  j["n2_data"] = o.m_transdata;
}

void from_json(const nlohmann::json& j, TransData& o) {
  j.at("n2_data").get_to(o.m_transdata);
}


}  // namespace model
}  // namespace amf
}  // namespace oai
